### ISSUE TITLE
Dependency conflict when attempting to add to project

### ISSUE THREAD

**Issue by CyMathew** [JanezStupar/drift_crdt#2]
I'm interested in using this package in my application but I'm having issues with adding it as a dependency.
I get the following error while running `flutter pub add drift_crdt`

```
flutter pub add drift_crdt
The current Dart SDK version is 3.1.2.

Because drift_crdt >=1.0.2 <1.0.7 depends on synchroflite ^0.1.1 and drift_crdt <1.0.2 depends on synchroflite ^0.1.0, drift_crdt <1.0.7 requires synchroflite ^0.1.0.
And because drift_crdt >=1.0.7 depends on synchroflite ^0.1.2, every version of drift_crdt requires synchroflite ^0.1.0.
Because drift_dev >=2.14.0 <2.15.0 depends on sqlparser ^0.33.0 and every version of synchroflite depends on sqlparser ^0.32.0, drift_dev >=2.14.0 <2.15.0 is incompatible with synchroflite.
Thus, drift_dev >=2.14.0 <2.15.0 is incompatible with drift_crdt.
And because drift_dev >=2.15.0 depends on drift >=2.15.0 <2.16.0, if drift_crdt any and drift_dev >=2.14.0 then drift >=2.15.0 <2.16.0.
And because drift >=2.14.1 depends on sqlite3 >=2.2.0 which requires SDK version >=3.2.0 <4.0.0, drift_crdt is incompatible with drift_dev >=2.14.0.
So, because project depends on both drift_crdt any and drift_dev ^2.14.0, version solving failed.
```

Here are my dependencies from `pubspec.yaml`:

```yaml
dependencies:
  flutter:
    sdk: flutter


 # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  connectivity_plus: ^5.0.2
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  get_it: ^7.6.7
  json_annotation: ^4.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1
  json_serializable: ^6.7.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  drift_dev: ^2.14.0
```

I use drift_dev as a dev dependency to auto generate RowClass/CompanionClasses. Please let me know  how I can resolve this issue. Thank you!
